#! /bin/bash
#=========================================================================
# Copyright (c) 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <client-name>

Dispalay info about the client

OPTIONS
  -h 
     display help

EXAMPLES
  $(basename $0) -h
  $(basename $0) tode

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"
  exit 1
fi
source ${GS_HOME}/bin/defGsDevKit.env
if [ "${GS_TODE_CLIENT}x" = "x" ] ; then
  echo "the GsDevKit_todeClient project has not been installed correctly or the"
  echo "GS_TODE_CLIENT environment variable has not been defined"
  exit 1
fi

while getopts "h" OPT ; do
  case "$OPT" in
    h) usage; exit 0 ;;
     *) usage; exit 1 ;;
  esac
done
shift $(($OPTIND - 1))

clientName=$1

echo "  $clientName	- tODE client"

scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

pushd $scriptDir >& /dev/null
  echo "	images:"
  for fileName in $(find . -maxdepth 1 -type d)
  do
    if [[ "$fileName" = "./todeClient*.image" ]] ; then
      imageName=`echo "$fileName" | cut -c 3- | cut -d'.' -f1`
      ${GS_GS_CLIENT_DEV_CLIENTS}/$clientName/clientInfo $clientName
    fi
  done

popd >& /dev/null

