#! /bin/bash
#=========================================================================
# Copyright (c) 2015,2016 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
#   MIT license: https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/license.txt
#=========================================================================

theArgs="$*"
source ${GS_HOME}/bin/private/shFeedback

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <client-name>

Dispalay info about the client

OPTIONS
  -h 
     display help

EXAMPLES
  $(basename $0) -h
  $(basename $0) tode

HELP
}

source ${GS_HOME}/bin/defGsDevKit.env
if [ "${GS_TODE_CLIENT}x" = "x" ] ; then
  exit_1_banner "the GsDevKit_todeClient project has not been installed correctly or the GS_TODE_CLIENT environment variable has not been defined"
fi

while getopts "h" OPT ; do
  case "$OPT" in
    h) usage; exit 0 ;;
    *) usage; exit_1_banner "Uknown option";;
  esac
done
shift $(($OPTIND - 1))

clientName=$1

echo "	$clientName"

scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

pushd $scriptDir >& /dev/null
 for fileName in $(find . -type f)
  do
    if [[ "$fileName" = ./${clientName}*.image ]] ; then
      imageName=`echo "$fileName" | cut -c 3-`
      echo "	  $imageName	(client)"
    elif [[ "$fileName" = ./todeClient*.image ]] ; then
      imageName=`echo "$fileName" | cut -c 3-`
      echo "	  $imageName	(tode client)"
    fi
  done

popd >& /dev/null
