#! /bin/bash
#=========================================================================
# Copyright (c) 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <client-name>

Delete the named client.

OPTIONS
  -h 
     display help

EXAMPLES
  $(basename $0) -h
  $(basename $0) tode

HELP
}

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"
  exit 1
fi
source ${GS_HOME}/bin/defGsDevKit.env

while getopts "h" OPT ; do
  case "$OPT" in
    h) usage; exit 0 ;;
    *) usage; exit 1 ;;
  esac
done
shift $(($OPTIND - 1))

clientName=$1

$GS_TODE_CLIENT/bin/deleteClient $clientName

echo "...finished $(basename $0)"
