#! /bin/bash
#=========================================================================
# Copyright (c) 2015, 2016 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
#   MIT license: https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/license.txt
#=========================================================================


source ${GS_HOME}/bin/defGsDevKit.env

clientName=$1

# answer the command to be used to delete the client directory ... that 
# way on windows the directory can be completely deleted

echo "$GS_TODE_CLIENT/bin/deleteClient $clientName"

