#! /bin/bash
#=========================================================================
# Copyright (c) 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================


source ${GS_HOME}/bin/defGsDevKit.env

clientName=$1

# answer the command to be used to delete the client directory ... that 
# way on windows the directory can be completely deleted

echo "$GS_TODE_CLIENT/bin/deleteClient $clientName"

