#! /bin/bash
#=========================================================================
# Copyright (c) 2015,2016 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
#   MIT license: https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/license.txt
#=========================================================================

theArgs="$*"
source ${GS_HOME}/bin/private/shFeedback
start_banner

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] [-p <postfix>] 
                      [-s <session-description-name>]
                      <client-name>
                      <script>

Launch todeClient image, evaluates <script> string, saves the image and quits.

OPTIONS
  -h 
     display help
  -p <postfix>
     Launch the tode client image created with a matching postfix. If
     the tode client image does not exist, build it.
  -s <session-description-name>
     Assume that client was created with -z option specified, use <session-description-name> to 
     override the default session name specified in the original <smalltalkCI-smalltalk.ston-path> file.

EXAMPLES
  $(basename $0) -h
  $(basename $0) tode "ZnZincServer startOn: 8080." # Evaluates script on the image named todeClient_0.image
  $(basename $0) -p _0 tode "ZnZincServer startOn: 8080." # Evaluates script on the image named todeClient_0.image

HELP
}

source ${GS_HOME}/bin/defGsDevKit.env
if [ "${GS_TODE_CLIENT}x" = "x" ] ; then
  exit_1_banner "the GsDevKit_todeClient project has not been installed correctly or the GS_TODE_CLIENT environment variable has not been defined"
fi
source ${GS_HOME}/bin/private/winRunPharoFunctions

scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

postFix=""
sessionName=""
postFixArg=""
script=""
while getopts "hp:s:" OPT ; do
  case "$OPT" in
    h) usage; exit 0 ;;
    p) postFix="${OPTARG}"; postFixArg=" -p ${OPTARG} ";;
    s) sessionName="${OPTARG}";;
    *) usage; exit_1_banner "Uknown option";;
  esac
done
shift $(($OPTIND - 1))

clientName=$1
imageName=${clientName}${postFix}

script=$2
if [ "${script}x" = "x" ]; then
	usage
	exit_1_banner "No script given"
fi

if [ ! -e $scriptDir/${imageName}.image ] ; then
  if [ ! -e $scriptDir/todeClient${postFix}.image ] ; then
    echo "The requested client image: $scriptDir/${imageName}.image does not exist"
    exit 1
  else
    # pre-existing old-style image
    imageName=todeClient${postFix}
  fi
fi

# Detect operating system
PLATFORM="`uname -sm | tr ' ' '-'`"
# Macs with Core i7 use the same software as older Macs
[ $PLATFORM = "Darwin-x86_64" ] && PLATFORM="Darwin-i386"

case "$PLATFORM" in
  Darwin-i386|Linux-x86_64) 
    pharoCmd="$scriptDir/pharo --headless"
    ;; 
  MSYS_NT*|MINGW32_NT*|MINGW64_NT*) 
    paroCmd="win_run_pharo $scriptDir --headless "
    ;;
  *) exit_1_banner "unsupported platform: $PLATFORM" ;;
esac

unset GEMSTONE_NRS_ALL

runScript="${script}.
SmalltalkImage current snapshot: true andQuit: true.
"

if [ "${sessionName}x" != "x" ]; then
  runScript="
SCIGemStoneServerConfigSpec defaultSessionName: '${sessionName}'.
${runScript}"
fi

$pharoCmd $scriptDir/${imageName}.image eval "${runScript}"

exit_0_banner "...finished"
