#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015, 2016 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
#   MIT license: https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/license.txt
#=========================================================================

theArgs="$*"
source ${GS_HOME}/bin/private/shFeedback
start_banner

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] <gemstone-version>

Notification that a new version of GemStone has been installed. Copy the GCI 
libraries to the approprate place for the various clients

OPTIONS
  -h display help

EXAMPLES
   $(basename $0) -h
   $(basename $0) 3.2.9

HELP
}

if [ $# -ne 1 ]; then
  usage; exit_1_banner "Missing required positional parameter"
fi
vers="$1"
scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$GS_HOME/bin/private/installGci -d $scriptDir -t pharo $vers

exit_0_banner "...finished"
