#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015, 2016 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
#   MIT license: https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/license.txt
#=========================================================================

theArgs="$*"
source ${GS_HOME}/bin/private/shFeedback
start_banner

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] [-f] <gemstone-version>

Notification that a new version of GemStone has been installed. Copy the GCI 
libraries to the approprate place for the various clients

OPTIONS
  -h display help
  -f force update of GCI libraries ... overwrite if they already exist

EXAMPLES
   $(basename $0) -h
   $(basename $0) 3.2.9
   $(basename $0) -f 3.2.9

HELP
}

forceOption=""
while getopts "hf" OPT ; do
  case "$OPT" in
    h) usage; exit 0;;
    f) forceOption=" -f ";;
    *) usage; exit_1_banner "Uknown option";;
  esac
done
shift $(($OPTIND - 1))

if [ $# -ne 1 ]; then
  usage; exit_1_banner "Missing required positional parameter"
fi
vers="$1"
scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$GS_HOME/bin/private/installGci $forceOption -d $scriptDir -t pharo $vers

exit_0_banner "...finished"
