#! /bin/bash
#=========================================================================
# Copyright (c) 2014, 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "              path: $0"
echo "================="

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] [-b <working-branch-name>]

OPTIONS
  -h 
     display help
  -b <working-branch-name>
     working branch name

EXAMPLES
  $(basename $0) -h
  $(basename $0) 

HELP
}

updateClone() {
  master="$1"
  theBranchName="$2"
  workingDir="$3"
  git --git-dir="$workingDir" checkout $master
  git --git-dir="$workingDir" pull origin $master
  git --git-dir="$workingDir" checkout $theBranchName
  git --git-dir="$workingDir" merge $master
}

set -e # exit on error
if [ "${GS_TODE_CLIENT}x" = "x" ] ; then
  echo "the GS_TODE_CLIENT environment variable needs to be defined"
  exit 1
fi
source ${GS_HOME}/bin/defGsDevKit.env

scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

${GS_TODE_CLIENT}/bin/updateGsDevKit $scriptDir

echo "...finished $(basename $0)"
