#! /bin/bash
#=========================================================================
# Copyright (c) 2015,2016 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
#   MIT license: https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/license.txt
#=========================================================================

theArgs="$*"
source ${GS_HOME}/bin/private/shFeedback
start_banner

usage() {
  cat <<HELP
USAGE: $(basename $0) [-h] [-b <working-branch-name>]

OPTIONS
  -h 
     display help

EXAMPLES
  $(basename $0) -h
  $(basename $0) 

HELP
}

if [ "${GS_TODE_CLIENT}x" = "x" ] ; then
  exit_1_banner "the GS_TODE_CLIENT environment variable needs to be defined"
fi
source ${GS_HOME}/bin/defGsDevKit.env

scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

${GS_TODE_CLIENT}/bin/updateGsDevKit $scriptDir

exit_0_bannter "...finished"
