#! /bin/bash

#! /bin/bash
#=========================================================================
# Copyright (c) 2015,2016 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#
#   MIT license: https://github.com/GsDevKit/GsDevKit_todeClient/blob/master/license.txt
#=========================================================================

theArgs="$*"
source ${GS_HOME}/bin/private/shFeedback
start_banner

source ${GS_HOME}/bin/defGsDevKit.env

if [ $# -lt 1 ]; then
  exit_1_banner "missing reguired argument <client-name>"
fi
clientName="$1"
scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

pushd $scriptDir >& /dev/null

  for imageName in $(find ./*.image -type f)
  do
    if [[ "$imageName" != ./Pharo.image ]] ; then
      stripped=`echo "$imageName" | cut -c 13-`
      postfix=${stripped%.*}
      posfixArg="-p $postfix"
      if [ "${postfix}x" = "x" ] ; then
        posfixArg=""
      fi
      $GS_TODE_CLIENT/bin/createClient -f $postfixArg $clientName
    fi
  done

popd >& /dev/null

exit_0_banner "...finished"
