#! /bin/bash
#=========================================================================
# Copyright (c) 2015 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
#=========================================================================

echo "================="
echo "   GsDevKit script: $(basename $0) $*"
echo "              path: $0"
echo "================="

set -e # exit on error
if [ "${GS_HOME}x" = "x" ] ; then
  echo "the GS_HOME environment variable needs to be defined"
  exit 1
fi
source ${GS_HOME}/bin/defGsDevKit.env

if [ $# -lt 1 ]; then
  echo "missing reguired argument <client-name>"; usage; exit 1
fi
clientName="$1"
scriptDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

pushd $scriptDir >& /dev/null

  for imageName in $(find ./*.image -type f)
  do
    stripped=`echo "$imageName" | cut -c 13-`
    postfix=${stripped%.*}
    $GS_TODE_CLIENT/bin/createClient -t -f $clientName -p $postfix
  done

popd >& /dev/null

echo "...finished $(basename $0)"
